### ISSUE TITLE
"snips-analytics"?

### ISSUE THREAD

**Issue by flatsiedatsie** [andrenatal/voice-addon#15]
While installing I saw something called "package snips-analytics" scroll by. Are you sure the software doesn't phone home to Snips?

**Comment by JDureau** [comment]
Snips always processes voice locally on your device, and no voice data or transcripts of your queries are ever sent back to Snips. However we do use the Snips analytics package to send a few simple heartbeat and analytics data (i.e. a daily heartbeat to say a device has been active, the category of intents used, the number of failed queries, and a few other high level metrics) so that Snips can detect errors and work on improvements to our product.

There is information about this and an option to enable and disable it on the console used by Mozilla to create the voice add-on you downloaded. This hadn't been opted-out from when you installed the add-on, and we realise now that this can raise issues when the person using the console to create the add-on is not the end user.

It is being disabled at the moment (pending PR), so heartbeat and analytics should be set to false by default if you update the add-on once the PR is merged.

We're working on an update with more transparency and controls around this for end users and will roll it out as soon as it's ready.

**Comment by flatsiedatsie** [comment]
Sounds good. I'm glad to hear I could somehow help out in the development.

How can I disable it for the time being?

**Comment by andrenatal** [comment]
Thanks @flatsiedatsie for reporting and @JDureau for fixing! I'll implement the routines to update the assistant's package and publish it tomorrow.

**Comment by flatsiedatsie** [comment]
It seems currently snips analytics is still enabled.

**Comment by andrenatal** [comment]
Hi @flatsiedatsie, in the new version (1.0.0), the required packages are now bundled and installed by the addon. Would you mind please testing it? Thanks!

**Comment by andrenatal** [comment]
Before doing it, is better to remove your current version of snips (apt-get remove snips*)
